### ISSUE TITLE
P02 Firebase - Gramar issue

### ISSUE THREAD

**Issue by soggybag** [MakeSchool-Tutorials/Sushi-Neko-Networking-SpriteKit-Swift#14]
Under the heading Permissions - This sentence is not right. I'm not sure what you are tying to say here - see the bold below.

Permissions
In a typical project you would want to lock down your permissions. **You might not might that anyone can read the high score table**. However, you probably only want 'authenticated' users to be able to modify (write) data.

**Comment by soggybag** [comment]
Might also be good to add a note: "We can dismiss the permissions warning for now."

**Comment by cocojoe** [comment]
Not sure why that happened, tided it up a bit.
