### ISSUE TITLE
P03 - Formatting Error 

### ISSUE THREAD

**Issue by esscbee** [MakeSchool-Tutorials/Sushi-Neko-Networking-SpriteKit-Swift#16]
<img width="882" alt="screen shot 2016-06-27 at 11 26 32 am" src="https://cloud.githubusercontent.com/assets/8846585/16391125/89049496-3c5a-11e6-8e4f-3bb082c272b1.png">

**Comment by cocojoe** [comment]
So this is relating to the original Sushi-Neko not Networking tutorial.  Fixed anyway, so closing.
