### ISSUE TITLE
P01 No such Module FirebaseDatabase

### ISSUE THREAD

**Issue by soggybag** [MakeSchool-Tutorials/Sushi-Neko-Networking-SpriteKit-Swift#4]
Not sure what's wrong. I ran pod install, import Firebase works. But the next line: import FirebaseDatabase show an error:

No such module FirebaseDatabase. 

Could be me. Opened from the Workspace, did a Clean, and Build?

**Comment by cocojoe** [comment]
Can you try pod update and let me know

**Comment by soggybag** [comment]
Did that, still have the same problem. I'm going to comment the this out, and continue. FirebaseDatabase might be contained in Firebase? I don't see any framework named FirebaseDatabase anywhere.
