### ISSUE TITLE
P02 Project Settings

### ISSUE THREAD

**Issue by soggybag** [MakeSchool-Tutorials/Sushi-Neko-Networking-SpriteKit-Swift#5]
There is a section that reads: 

**Project settings**

Great, there is one last step. You need to download a GoogleService-Info.plist from Firebase and add this to your project.

[action] Navigate to Firebase Project Settings and run through the iOS app process.

It is not clear what to do here. I can't find "Project settings" anywhere from this step.

**Comment by soggybag** [comment]
Seems I needed to go to the root of my project on the firebase site, click the blue circle, and follow the instructions. This required that I get my app bundle id.

**Comment by cocojoe** [comment]
I've made it a bit more obvious

**Comment by cocojoe** [comment]
Please sync and re-read to ensure it makes sense.

**Comment by soggybag** [comment]
Seems we need to say click the blue **button** at this step.

**Comment by cocojoe** [comment]
No, the tutorial as stated in first chapter will not be that hand holdy.  However, I have added more actions to make it clearer.
