### ISSUE TITLE
P2 Image ontop of text

### ISSUE THREAD

**Issue by AnnMic** [MakeSchool-Tutorials/Sushi-Neko-Networking-SpriteKit-Swift#8]
In the end of section "CocoaPods setup"

The image is on top of the text

**Comment by AnnMic** [comment]
This also happens in section "Xcode workspace"

**Comment by AnnMic** [comment]
Actually this happens at tons of places

**Comment by dionlarson** [comment]
Fixed in b9b02073e72ff8a6766f165de266c993a112282a.

Let me know if you see any others!
